### ISSUE TITLE
Inventory ClicEvent

### ISSUE THREAD

**Issue by Punishkey** [BetonQuest/RPGMenu#11]
## Bug report

**Spigot version:** `<!-- put your servers spigot version here -->`
Latest 1.13.2
**RPGMenu version:** `<!-- put your RPGMenu version here -->`
3.0
**BetonQuest version:** `<!-- put your BetonQuest version here -->`
v2.0-preview.17
### Description:

left click that leads to another menu, this takes me but in console pulls error
```
<!--if you have errors in console include them here,
remove this section otherwise-->
``
[13:34:08] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RPGMenu v3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2144) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-282dad1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-282dad1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftInventory.setContents(CraftInventory.java:85) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	at de.ungefroren.rpgmenu.OpenedMenu.update(OpenedMenu.java:142) ~[?:?]
	at de.ungefroren.rpgmenu.OpenedMenu.update(OpenedMenu.java:149) ~[?:?]
	at de.ungefroren.rpgmenu.OpenedMenu.onClick(OpenedMenu.java:187) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
	... 15 more
```

### How to reproduce:

``
left clic on icon in rpgmenu.
### Checklist:

- [ x ] I included all versions (use `/version` command)
- [ x ] I made sure there aren't duplicates of this report [(use Search)](https://github.com/joblo2213/RPGMenu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABug+)
- [ x ] I made sure I am using an up-to-date version of RPGMenu
- [ x ] I made sure the bug/error is not caused by any other plugin

**Comment by SaltyAimbOtter** [comment]
Dublicate of #8

**Comment by Punishkey** [comment]
mm i dont see update. closed
