### ISSUE TITLE
Error with RPGMenu

### ISSUE THREAD

**Issue by Momonche** [BetonQuest/RPGMenu#15]
## Bug report

**Spigot version:** `Paper git-paper-343 (MC: 1.15.2)`

**BetonQuest version:** `BetonQuest v1.12.0-DEV-41`

### Description:
Hello !
When certains players try to open a menu with RPGMenu there is an error and the menu doesn't open

```
[10:24:06 WARN]: [BetonQuest] Task #7382512 for BetonQuest v1.12.0-DEV-41 generated an exception
java.lang.AbstractMethodError: pl.betoncraft.betonquest.api.QuestEvent.execute(Ljava/lang/String;)Ljava/lang/Void;
at pl.betoncraft.betonquest.api.QuestEvent.execute(QuestEvent.java:45) ~[?:?]
at pl.betoncraft.betonquest.api.ForceSyncHandler.handle(ForceSyncHandler.java:68) ~[?:?]
at pl.betoncraft.betonquest.api.QuestEvent.fire(QuestEvent.java:158) ~[?:?]
at pl.betoncraft.betonquest.BetonQuest.event(BetonQuest.java:191) ~[?:?]
at pl.betoncraft.betonquest.events.FolderEvent$1.run(FolderEvent.java:92) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-343]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-343]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.2.jar:git-Paper-343]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-343]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1180) ~[patched_1.15.2.jar:git-Paper-343]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:969) ~[patched_1.15.2.jar:git-Paper-343]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

### How to reproduce:
I don't really know how to reproduce, only happens on certains player
(If the error is not revelant, I can make more test if you want)

**Comment by Wolf2323** [comment]
A new RPGMenu jar was added in Discord, with that is should work: https://cdn.discordapp.com/attachments/410168445427253268/724011156250951680/RPGMenu.jar
