### ISSUE TITLE
Could not pass event LoadDataEvent

### ISSUE THREAD

**Issue by aziztulaganov** [BetonQuest/RPGMenu#18]
**Spigot version:** This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**RPGMenu version:** 4.0

**BetonQuest version:** 1.11

**Description:**
I have the next problem:

[12:15:18 ERROR]: Could not pass event LoadDataEvent to RPGMenu v4.0
java.lang.NoClassDefFoundError: pl/betoncraft/betonquest/id/ConditionID
at de.ungefroren.rpgmenu.RPGMenu.reloadData(RPGMenu.java:220) ~[?:?]
at de.ungefroren.rpgmenu.ReloadListener.onReload(ReloadListener.java:34) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at pl.betoncraft.betonquest.BetonQuest.loadData(BetonQuest.java:939) ~[?:?]
at pl.betoncraft.betonquest.BetonQuest$1.run(BetonQuest.java:719) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassNotFoundException: pl.betoncraft.betonquest.id.ConditionID
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
... 16 more

So plugin doesn't show me any menu in the game.

**Comment by SaltyAimbOtter** [comment]
This is probably caused by using an outdated BQ version.
